version: '3.4'

services:
  kestrel:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../shared/GoogleStorage:/root/.local/share/google-filedatastore/
      - ../shared/uploads:/app/uploads/
      - ../shared/Data:/app/Data
      - ../shared/Certs:/app/Certs
