version: '3.4'

services:
  kestrel:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44371
    ports:
      - "50613:80"
      - "44371:443"
